version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2

    groups:
      Minor Development Deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      Major Development Deps:
        dependency-type: "development"
        update-types:
          - "major"
      Minor Production Deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      Major Production Deps:
        dependency-type: "production"
        update-types:
          - "major"
