branch_whitelist = [ "main" ]
from_latest_tag = false
ignore_merge_commits = true
tag_prefix = "v"

pre_bump_hooks = [
  "npm version {{version}} --no-git-tag-version",
  "npm install --lockfile-only"
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""

[commit_types]
build = { changelog_title = "ğŸ—ï¸ Build System" }
chore = { changelog_title = "ğŸ§¹ Miscellaneous Chores" }
ci = { changelog_title = "ğŸ“¦ Continuous Integration" }
docs = { changelog_title = "ğŸ“– Documentation" }
feat = { changelog_title = "ğŸŒŸ Features", bump_minor = true }
fix = { changelog_title = "ğŸ› Bug Fixes", bump_patch = true }
perf = { changelog_title = "âš¡ Performances Improvements" }
refactor = { changelog_title = "â™»ï¸ Refactoring" }
test = { changelog_title = "ğŸ§ª Tests" }

[changelog]
authors = [
  { username = "sylver", signature = "Richard Kemp" },
  { username = "louis-lamoureux", signature = "Louis-P. Lamoureux" }
]
owner = "fincura-ai"
path = "CHANGELOG.md"
remote = "github.com"
repository = "stedi-sdk-js"
template = "remote"
